# Name of the project
PROJECT_NAME = Sun_Tracking_Solar_Panel

#Doxyfile folder
DOC = documentation

#All source code files
SRC = Project_main.c\

#Document files
DOCUMENTATION_OUTPUT = documentation/html
